### ISSUE TITLE
Add DigitalLink#pending? / #ready?

### ISSUE THREAD

**Issue by fschwahn** [denkungsart/solidus_digital#6]
Because digital links are not available right away with DRM, user has to check for `digital_link.attachment.exists?` - a more intuitive API would be `ready?` & `pending?`.

**Comment by shiroginne** [comment]
I'm closing this issue due to https://github.com/denkungsart/solidus_digital/commit/d332fdc2bb0fc8cfc57d24f12091d330134337ef
